app/routes.py
"""
 Primary routes file
 Contains all the important routes for the application, along with some helper functions
"""

from flask import render_template
from flask import request
from flask import Blueprint
from flask import session

from flask_login import current_user
from flask_login import login_required

from flask_socketio import emit

from app.user import User
from app.flask_shared_modules import mongo
from app.flask_shared_modules import socketio
from app.flask_shared_modules import esiapp
from app.flask_shared_modules import esiclient
from app.routes_helpers import (add_db_sid, authenticated_only, update_token, EsiException,
                                id_from_name, EsiError, remove_db_sid, emit_to_char )
from app.background_fleet import (background_fleet, update_fleet_metadata)
from app.version import version

import json
import copy
import logging

main_pages = Blueprint('main_pages', __name__)

@main_pages.route("/app")
@login_required
def main_app():
    return render_template("app.html")

@main_pages.route("/")
def index():
    return render_template("index.html", version=version)
    
@main_pages.route('/faq')
def faq():
    return render_template('faq.html')
    
@main_pages.route('/help')
def help():
    return render_template('help.html')

@socketio.on('connect')
def handle_connect():
    logging.debug('client connected')

@socketio.on('connect', namespace='/client')
def handle_client_connect():
    logging.debug('client in /client connected')
    
@socketio.on('disconnect')
def handle_disconnect():
    logging.debug('Client disconnected, removing sid from db')
    if current_user.is_authenticated:
        remove_db_sid(current_user.character_id, request.sid)
    
@socketio.on('disconnect', namespace='/client')
def handle_client_disconnect():
    try:
        _id = session['user'].character_id
        _filter = {'id': _id}
    except KeyError:
        socket_guid = request.cookies.get('socket_guid', 0)
        _filter = {'socket_guid': socket_guid}
    doc = mongo.db.characters.find_one(_filter)
    if doc != None and doc['client_sid'] == request.sid:
        remove_client_from_fleets(doc['id'])

@socketio.on('kick')
@authenticated_only
def handle_kick(_id):
    update_token(current_user)
    op = esiapp.op['delete_fleets_fleet_id_members_member_id'](
        member_id=_id,
        fleet_id=current_user.get_fleet_id()
    )
    request = esiclient.request(op)
    if request.status != 204:
        error_string = request.data['error'] if request.data else str(request.status)
        logging.error('error performing kick for %s', _id)
        logging.error('error is: %s', error_string)
        emit('error', error_string)
        return
    emit('info', 'member kicked')

@socketio.on('move')
@authenticated_only
def handle_move(info):
    movement = {'role': info['role']}
    if info['squad'] > 0:
        movement['squad_id'] = info['squad']
    if info['wing'] > 0:
        movement['wing_id'] = info['wing']
    update_token(current_user)
    op = esiapp.op['put_fleets_fleet_id_members_member_id'](
        member_id=info['id'],
        fleet_id=current_user.get_fleet_id(),
        movement=movement
    )
    request = esiclient.request(op)
    if request.status != 204:
        error_string = request.data['error'] if request.data else str(request.status)
        logging.error('error performing move for %s', info['id'])
        logging.error('error is: %s', error_string)
        emit('error', error_string)
        return
    emit('info', info['name']+' moved to '+info['role'])

@socketio.on('register_client', namespace='/client')
def register_client(info={}):
    socket_guid = info.get('socket_guid', request.cookies.get('socket_guid', 0))
    name = info.get('name', request.cookies.get('name', None))
    _filter = {'socket_guid': socket_guid}
    doc = mongo.db.characters.find_one(_filter)
    if doc != None and doc['name'] == name:
        _filter = {'id': doc['id']}
        data_to_update = {}
        data_to_update['version'] = info.get('version', 'v2.4.0')
        data_to_update['client_sid'] = request.sid
        update = {"$set": data_to_update}
        mongo.db.characters.update_one(_filter, update)
        session['user'] = User(character_id=doc['id'], mongo=mongo)
        emit('client_registered')
    
@socketio.on('peld_data', namespace='/client')
def handle_peld_data(entry):
    if 'owner' not in entry['entry']:
        entry['entry']['owner'] = request.cookies['name']
    if entry['entry']['shipType'] != entry['entry']['pilotName']:
        entry['entry']['shipType'] = entry['entry']['shipType'].strip('*')
        entry['entry']['shipTypeId'] = id_from_name(entry['entry']['shipType'])
    else:
        entry['entry'].pop('shipType')
    fleet = process_incoming_peld(socket_guid=entry.get('socket_guid', None), name=entry['entry']['owner'])
    if 'socket_guid' in entry:
        entry.pop('socket_guid')
    if fleet:
        emit_peld_data(json.dumps(entry), fleet)

def emit_peld_data(entry, fleet):
    for char_id in fleet['connected_webapps']:
        char_doc = mongo.db.characters.find_one({'id': char_id})
        if char_id == fleet['fc_id'] or fleet['fleet_access'][char_doc['fleet_role']]:
            emit_to_char('peld_data', entry, sids=char_doc['sid'])
    if fleet['client_access']:
        for char_id in fleet['connected_clients']:
            char_doc = mongo.db.characters.find_one({'id': char_id})
            if char_doc and 'sid' in char_doc:
                socketio.emit('peld_data', entry, room=char_doc['client_sid'], namespace='/client')
    
@socketio.on('peld_check', namespace='/client')
def handle_peld_check(data={}):
    fleet = process_incoming_peld(update_metadata=True, **data)
    if fleet:
        data = {
            'connected': len(fleet['connected_clients']),
            'total': len(fleet['members']),
            'client_access': fleet['client_access'],
            'fc_connected': fleet['fc_id'] in fleet['connected_webapps']
        }
        emit('peld_check', json.dumps(data))
            
def process_incoming_peld(update_metadata=False, socket_guid=None, name=None):
    if not socket_guid:
        socket_guid = request.cookies.get('socket_guid', 0)
        name = request.cookies.get('name', None)
    try:
        _id = session['user'].character_id
    except KeyError:
        _filter = {'socket_guid': socket_guid}
        doc = mongo.db.characters.find_one(_filter)
        if doc != None and doc['name'] == name:
            _id = doc['id']
            session['user'] = User(character_id=doc['id'], mongo=mongo)
        else:
            return None
    if update_metadata:
        try:
            return update_fleet_metadata(session['user'], client=True)
        except (EsiError, EsiException) as e:
            if str(e) == 'Character is not in a fleet':
                emit('peld_error', 'Character is not in a fleet')
                remove_client_from_fleets(_id)
            return None
    return mongo.db.fleets.find_one({'connected_clients': _id})

def remove_client_from_fleets(char_id):
    fleets = mongo.db.fleets.find({'connected_clients': char_id})
    if fleets is not None:
        for fleet in fleets:
            fleet['connected_clients'].remove(char_id)
            update = {'$set': {'connected_clients': fleet['connected_clients']}}
            mongo.db.fleets.update_one({'id': fleet['id']}, update)

@socketio.on('register_fleet_handler')
@authenticated_only
def handle_fleet():
    current_user.sid = request.sid
    current_user.set_fleet_id(0)
    add_db_sid(current_user.character_id, request.sid)

    try:
        fleet_doc = update_fleet_metadata(current_user)
    except (EsiError, EsiException) as e:
        emit('exception', str(e))
        return

    if fleet_doc['fc_id'] == current_user.character_id:
        fleet_settings = {
            'fleet_access': fleet_doc['fleet_access'],
            'boss': fleet_doc['fc_id'],
            'client_access': fleet_doc['client_access']
        }
        fleet_settings_serial = json.dumps(fleet_settings)
        emit('fleet_settings', fleet_settings_serial)
    
    user = copy.copy(current_user)
    sid = request.sid
    socketio.start_background_task(target=lambda: background_fleet(user, sid))

@socketio.on('fleet_settings')
@authenticated_only
def handle_fleet_settings(fleet_settings):
    fleet_settings = json.loads(fleet_settings)
    _filter = {'id': current_user.get_fleet_id()}
    fleet_doc = mongo.db.fleets.find_one(_filter)

    if fleet_doc['fc_id'] != current_user.character_id:
        emit('error', 'Only Fleet Boss may change fleet settings')
        return

    data_to_update = {
        'fleet_access': fleet_settings['fleet_access'],
        'client_access': fleet_settings['client_access']
    }
    update = {'$set': data_to_update,
              '$currentDate': {'updated_time': {'$type': 'date'} }
             }
    mongo.db.fleets.update_one(_filter, update)

templates/app.html
{% extends "layout.html" %}
{% block content %}
<div id="error" class="w-100 justify-content-center">
</div>
<div id="character_id" data-id="{{ current_user.character_id }}" class="d-none"></div>
<div id="content" class="h-100 d-flex">
  <h3 class="text-center">Loading...</h3>
</div>
<div id="settings">
</div>
{% endblock %}

templates/error.html
{% extends "layout.html" %}
{% block content %}
<div class="m-2">{{error}}</div>
{% endblock %}

templates/faq.html
{% extends "layout.html" %}
{% block content %}
<div class="px-1 m-2">
  <h3 class="border-bottom border-secondary text-center my-3">FAQ</h3>

  <div class="accordion mb-3" id="faqAccordion_disabled">
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#faq1">
          <h5 class="mb-0">
            How do I use this site?
          </h5>
        </button>
      </div>
      <div id="faq1" class="collapse show">
        <div class="card-body pt-2">
          See the <a href="/help">help page</a>.
        </div>
      </div>
    </div>
    
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#faq2">
          <h5 class="mb-0">
              I'm having a problem or want a new feature, what do I do?
          </h5>
        </button>
      </div>
      <div id="faq2" class="collapse show">
        <div class="card-body pt-2">
          Look at the open issues <a href="https://github.com/ArtificialQualia/PELD-Server/issues">here</a>.<br />
          If you think this is an unknown bug or new feature, open a <a href="https://github.com/ArtificialQualia/PELD-Server/issues/new">New Issue</a>.
        </div>
      </div>
    </div>
    
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#faq3">
          <h5 class="mb-0">
            Why does it take so long for fleet updates to show up?
          </h5>
        </button>
      </div>
      <div id="faq3" class="collapse show">
        <div class="card-body pt-2">
          <p class="mb-1">Updates come as fast as CCP will allow.<br />
            This is supposed to be every 5 seconds, but for some fleet statistics it takes longer because CCP gives old obsolete data.<br />
            In general, it takes about:</p>
          <ul class="mb-1">
            <li>{{'<'}}5 seconds for fleet member changes (join/leave/move)</li>
            <li>~30 seconds for fleet ship changes</li>
            <li>~30 seconds for fleet location updates</li>
          </ul>
          NOTE: PELD combat data updates are sent immediately and are in real time.
        </div>
      </div>
    </div>
    
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#faq4">
          <h5 class="mb-0">
            Can I see your source code?
          </h5>
        </button>
      </div>
      <div id="faq4" class="collapse show">
        <div class="card-body pt-2">
          Yes, this project is open source, just like PELD.  View it <a href="https://github.com/ArtificialQualia/PyEveLiveDPS">here</a>.
        </div>
      </div>
    </div>
    
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#faq5">
          <h5 class="mb-0">
            Opsec is important to me, what data do you store on the server?
          </h5>
        </button>
      </div>
      <div id="faq5" class="collapse show">
        <div class="card-body pt-2">
          <p class="mb-1">Only the bare minimum.  Almost all data simply passes through the server from either a PELD client, or from ESI, to the FC.  It is not stored.<br />
            To reiterate, the highly opsec things like PELD combat data, fleet location, fleet ship types, are NOT stored on the server.<br />
            What is stored:</p>
          <ul class="mb-1">
            <li>Public information like names, item IDs, etc.</li>
            <li>ESI Tokens (these are revoked when you log off)</li>
            <li>A list of fleet members (only character IDs) for an FC's fleet.  This is required to verify that someone connecting through PELD does indeed belong to your fleet.  Fleet data is automatically deleted after 24 hours.</li>
          </ul>
          If you don't trust any server that you don't control, you can spin up your own PELD-Fleet instance.  Read more about that <a href="https://github.com/ArtificialQualia/PELD-Server/wiki/Deployment">here</a>.
        </div>
      </div>
    </div>
    
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#faq6">
          <h5 class="mb-0">
            What is your tech stack?
          </h5>
        </button>
      </div>
      <div id="faq6" class="collapse show">
        <div class="card-body pt-2">
          <ul class="mb-0">
            <li>Flask (python webserver)</li>
            <li>React (javascript framework)</li>
            <li>MongoDB (nosql database)</li>
            <li>Nginx (load balancer, reverse proxy)</li>
            <li>Eventlet (websocket/concurrent network server)</li>
            <li>Redis (session caching)</li>
            <li>Docker (deployments/containerization)</li>
          </ul>
        </div>
      </div>
    </div>
    
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#faq7">
          <h5 class="mb-0">
            Who made this?
          </h5>
        </button>
      </div>
      <div id="faq7" class="collapse show">
        <div class="card-body pt-2">
          <a href="https://evewho.com/pilot/Demogorgon+Asmodeous">Demogorgon Asmodeous</a>.  View my github <a href="https://github.com/ArtificialQualia">here</a>.  ISK donations welcome.
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/help.html
{% extends "layout.html" %}
{% block content %}
<div class="px-1 m-2">
  <h3 class="border-bottom border-secondary text-center my-3">Help</h3>

  <div class="accordion mb-3" id="faqAccordion_disabled">
    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#help1">
          <h5 class="mb-0">
            Connecting PyEveLiveDPS to PELD-Fleet
          </h5>
        </button>
      </div>
      <div id="help1" class="collapse">
        <div class="card-body pt-2">
          <div class="d-inline-flex align-items-center">
            <img class="portrait rounded mr-1" src="{{ url_for('static', filename='img/peld-login.gif') }}">
            <div class="w-100 d-flex flex-column justify-content-center">
              <ol>
                <li>Start your EVE client</li>
                <li>Start PELD</li>
                <li>Choose the correct character in the 'Character...' menu in PELD</li>
                <li>From the main 'File...' menu, choose 'Fleet Mode'</li>
                <li>Verify the character at the top of the 'Fleet Mode' menu is the one you want to use</li>
                <li>In 'Server to use', either leave the default 'peld-fleet.com' or enter in your alliance's PELD-Server URL (ask your FC)</li>
                <li>If you are not the FC, leave the 'Fleet Member' radio button checked</li>
                <li>If you are participating in a large fleet fight, consider checking the 'low CPU mode' option
                  <br />
                  This will drastically reduce the CPU useage of PELD, but will prevent you from seeing your own combat statistics locally
                </li>
                <li>Hit 'Login', a webpage will open for you to login via ESI, and a notification will pop up letting you know PELD is awaiting your login</li>
                <li>A few seconds after you login, PELD will close the 'awaiting login' notification, and then you can play EVE normally!</li>
              </ol>
              PELD will automatically detect your fleet and send your combat statistics to the FC, you don't need to restart 'Fleet Mode' if you leave/join a new fleet.
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#help2">
          <h5 class="mb-0">
            Fleet member management
          </h5>
        </button>
      </div>
      <div id="help2" class="collapse">
        <div class="card-body pt-2">
          <div class="d-inline-flex align-items-center">
            <img class="portrait rounded mr-1" src="{{ url_for('static', filename='img/help-fleet-members.gif') }}">
            <div class="w-100 d-flex flex-column justify-content-center">
              <h5>Moving members</h5>
              <ol>
                <li>Drag and drop any fleet member to move them</li>
                <li>Move your fleet member over a wing/squad to expand the wing/squad</li>
                <li>The fleet panel will take a few seconds to update</li>
              </ol>
              <h5>Kicking members</h5>
              <ol>
                <li>Click on any fleet member</li>
                <li>Choose 'Kick Member' from the dropdown</li>
                <li>The fleet panel will take a few seconds to update</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#help3">
          <h5 class="mb-0">
            Fleet statistics
          </h5>
        </button>
      </div>
      <div id="help3" class="collapse">
        <div class="card-body pt-2">
          <div class="d-inline-flex align-items-center">
            <img class="portrait rounded mr-1" src="{{ url_for('static', filename='img/help-fleet-stats.gif') }}">
            <div class="w-100 d-flex flex-column justify-content-center">
              <h5>Statistics Details</h5>
              <div class="mb-3">Hover over any number in the Fleet Statistics panel to get a list of members the stat applies to</div>
              <h5>Move Statistics</h5>
              <div>Drag and drop any Fleet Statistic card to re-order them</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#help4">
          <h5 class="mb-0">
            PELD Data
          </h5>
        </button>
      </div>
      <div id="help4" class="collapse">
        <div class="card-body pt-2">
          <div class="d-inline-flex align-items-center">
            <img class="portrait rounded mr-1" src="{{ url_for('static', filename='img/help-peld-data.gif') }}">
            <div class="w-100 d-flex flex-column justify-content-center">
              <h5>Reorder Data</h5>
              <div class="mb-3">
                Drag and drop the title of any PELD Data card to reorder them, or change the column they are in
                <br />
                If all the PELD Data cards are in one column, the column will expand to take up the whole panel
                <br />
                NOTE: Within a data card, entries are ordered from highest value to lowest value
              </div>
              <h5>Change Settings</h5>
              <div>
                It is highly recommended to verify your PELD settings before you start combat
                <br />
                Click the gear next to 'PELD Data' to view/change your settings
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#help5">
          <h5 class="mb-0">
            PELD Settings
          </h5>
        </button>
      </div>
      <div id="help5" class="collapse">
        <div class="card-body pt-2">
          <div class="d-inline-flex align-items-center">
            <img class="portrait rounded mr-1" src="{{ url_for('static', filename='img/help-peld-settings.gif') }}">
            <div class="w-100 d-flex flex-column justify-content-center">
              <div class="mb-3">PELD Settings are saved to your webbrowser and persist across PELD-Fleet sessions</div>
              <h5>Average Values over (x) Seconds</h5>
              <div class="mb-3">
                This is a critical setting.  This is how long 'hits' will stay on your screen, and affects how DPS is calculated.
                <br />
                For instance, if you choose a value of 30 seconds, and a Hurricane hits for 3000 damage, you will see '100' DPS and the hit will remain on your screen for 30 seconds.
              </div>
              <h5>Expand PELD Data Entries</h5>
              <div class="mb-3">
                If checked, each new combat entry will be automatically expanded so you can see a breakdown of who was involved and the weapons they used.
              </div>
              <h5>Colors</h5>
              <div>
                This changes the color that appears for each entry and card header.  Click on a color to change it.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="m-2 d-flex flex-column align-items-center">
  <div class="d-flex flex-column w-75 mb-2">
    <h2 class="align-self-center">PELD-Fleet</h2>
    <h5 class="text-muted align-self-center">{{ version }}</h5>
    <div class="jumbotron p-3">
      <img class="figure-img img-fluid rounded border border-secondary" src="{{ url_for('static', filename='img/peld-example.png') }}" />
    </div>
    <h3 class="border-bottom border-secondary">What is this?</h3>
    <p class="w-100">
        PELD-Fleet is the web component for the fleet networking feature of <a href="https://github.com/ArtificialQualia/PyEveLiveDPS">PyEveLiveDPS (PELD)</a>.
        <br />
        It provides a webpage for FCs to do fleet management and read output of combat stats from all of their fleet members running PELD.
        <br />
        This allows FCs to see stats like fleet location, and whom/what their fleet are attacking in realtime.
        This helps FCs decide on who to primary, to ensure line members are engaging the correct targets, make sure logi chains are correct, etc.
    </p>
    <br />
    <h3 class="border-bottom border-secondary">How do I use it?</h3>
    <p class="w-100">
      See the <a href="/help">help</a> page for some tutorials.
      <br />
      An FC can use PELD-Fleet without any fleet members running PELD itself, but you will only get combat data from fleet members running PELD.
      <br />
      The FC will need the Fleet Boss role to use this site. This is due to limitations set by CCP.
      <br />
      <br />
      If you want to get started immediately, login now:
      <br />
      <a href="/app">
        <img class="mt-1" src="{{ url_for('static', filename='img/eve-login.png') }}" />
      </a>
    </p>
    <br />
    <h3 class="border-bottom border-secondary">Who made this?</h3>
    <div class="mb-3">
      <div class="d-flex align-items-center">
        <img class="portrait rounded mr-1" width="128" height="128" src="https://image.eveonline.com/Character/1858883174_128.jpg">
        <div class="w-100 d-flex flex-column justify-content-center">
          <div>
            <a href="https://evewho.com/pilot/Demogorgon+Asmodeous">Demogorgon Asmodeous</a>
            <br>
            <a href="https://github.com/ArtificialQualia">View my github</a> (contains all the source code from both PELD and PELD-Fleet)
            <br>
            ISK donations welcomed.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/layout.html
<!doctype html>
<html>
  <head>
    <title>PELD-Fleet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <style>
      body {display: none; background-color: #222}
    </style>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/peld.css') }}">
  </head>
  <body class="d-flex flex-column">
    <div class="navbar navbar-expand-md navbar-dark bg-primary py-1">
      <a href="{{ url_for('main_pages.index') }}" class="navbar-brand">
        <img src="{{ url_for('static', filename='img/favicon.ico') }}" width="32" height="32">
        <span class="align-middle pl-1">+</span>
        <svg height="32" width="32">
          <polyline points="2,11 16,3 30,11" class="chevron-logo"></polyline>
          <polyline points="2,20 16,12 30,20" class="chevron-logo"></polyline>
          <polyline points="2,29 16,21 30,29" class="chevron-logo"></polyline>
          ?
        </svg>
        <span class="align-middle">PELD-Fleet</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/app">App</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/faq">FAQ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/help">Help</a>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <div class="dropdown d-inline-block">
              {% if current_user.is_authenticated %}
              <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" data-boundary="viewport">
                  <img class="portrait rounded mr-1" src="https://image.eveonline.com/Character/{{ current_user.character_id }}_32.jpg" />{{ current_user.character_name }}
                  <span class="caret"></span>
                </a>
              <div class="dropdown-menu dropdown-menu-right" style="min-width: 0px;z-index: 1030;">
                <a href="{{ url_for('sso_pages.logout') }}" class="dropdown-item white-link"> Logout</a>
              </div>
              {% else %}
              <a class="nav-link" href="/app">
                <img src="{{ url_for('static', filename='img/eve-login.png') }}" />
              </a>
              {% endif %}
            </div>
          </li>
        </ul>
        {% block header %}
        {% endblock %}
      </div>
    </div>
    {% block content %}{% endblock %}
    <script src="{{ url_for('static', filename='dist/bundle.js') }}" type="text/javascript"></script>
  </body>
</html>